import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AuthLoaderWrapper from "@/common/AuthLoaderWrapper";
import QueryProvider from "@/common/QueryProvider";
import { SocketProvider } from "@/context/SocketContext";
import RealtimeNotificationListener from "@/components/notifications/RealtimeNotificationListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <ClerkProvider>
        <QueryProvider>
          <SocketProvider>
            <AuthLoaderWrapper>
            {children}
            </AuthLoaderWrapper>
            <RealtimeNotificationListener />
          </SocketProvider>
        </QueryProvider>
      </ClerkProvider>  
      </body>
    </html>
  );
}
